---
title: "test_plotly"
author: "Rahul Hosalli"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

library(plotly)
library(flexdashboard)
```

```{r}
data("ny_noaa")
noaa_df <- ny_noaa %>%
  janitor::clean_names() %>%
  
  separate(date, into = c("year", "month", "date"), sep = "-") %>% 
  
  mutate(year = as.integer(year),
         month = as.integer(month),
         date = as.integer(date),
         
         tmax = as.integer(tmax)/10,
         tmin = as.integer(tmin)/10,
         prcp = prcp/10)
```

```{r}
noaa_df_sam <-
  noaa_df %>%
  slice_sample(n=2000) %>%
   mutate(month_name = factor(month.name[month], levels = month.name))

plot1_df<- noaa_df_sam %>%
  mutate(month_name = month.name[month]) %>%
  group_by(id, year, month_name) %>% 
  summarize(
    tmax_avg = mean(tmax)
  )

noaa_df_sam  %>%
  mutate(month_name = factor(month.name[month], levels = month.name)) %>%
  plot_ly(y = ~tmax, type = "box", color =  ~month_name, alpha = 0.5)


plot2 <-noaa_df_sam %>%
  
```
